#!/usr/bin/env python3
"""Guarded one-time edits of native source; never regenerates existing child sheets."""
from pathlib import Path
import json
import re
import shutil
from pr17_native import Drawing, DST, expressions, migrate, STAGES


def replace_once(text,old,new):
    if text.count(old)!=1:raise ValueError('unexpected edit context: '+old[:100])
    return text.replace(old,new,1)


def block(text,marker,offset=0):
    start=text.index(marker,offset);depth=0;quoted=escaped=False
    for i in range(start,len(text)):
        c=text[i]
        if quoted:
            if escaped:escaped=False
            elif c=='\\':escaped=True
            elif c=='"':quoted=False
        elif c=='"':quoted=True
        elif c=='(':depth+=1
        elif c==')':
            depth-=1
            if depth==0:return start,i+1,text[start:i+1]
    raise ValueError('unbalanced expression')


def modify_ldo(text,name):
    marker='(symbol "'+name+'"'
    if marker not in text:return text
    start,end,root=block(text,marker);hits=[]
    for m in re.finditer(r'\(pin power_out line',root):
        a,b,pin=block(root,'(pin power_out line',m.start())
        if '(number "12"' in pin:hits.append((a,b,pin))
    if len(hits)!=1:raise ValueError('expected one internally duplicated OUT12 in '+name)
    a,b,pin=hits[0]
    root=root[:a]+pin.replace('(pin power_out','(pin passive',1)+root[b:]
    return text[:start]+root+text[end:]


def power_status_sheet():
    d=Drawing('41_power_status','HOST-REFERENCED POWER STATUS: no expansion-rail pull-up on HIL_FAULT_N')
    d.ic('MMBT3904_POWER_STATUS',[(1,'B','input'),(2,'E','passive')],[(3,'C','open_collector')])
    src='https://assets.nexperia.com/documents/data-sheet/MMBT3904.pdf'
    d.add('MMBT3904_POWER_STATUS','Q401','MMBT3904,215 / default fault sink',228.6,88.9,{1:'FAULT_BASE',2:'GND',3:'HIL_FAULT_N'},'Package_TO_SOT_SMD:SOT-23',src)
    d.add('MMBT3904_POWER_STATUS','Q402','MMBT3904,215 / qualified release',88.9,154.94,{1:'RELEASE_BASE',2:'GND',3:'FAULT_BASE'},'Package_TO_SOT_SMD:SOT-23',src)
    d.r('R552','10k / HOST ARM referenced pull-up',330.2,50.8,'HIL_ARM','HIL_FAULT_N')
    d.r('R553','47k / default fault bias',88.9,60.96,'HIL_ARM','FAULT_BASE')
    d.r('R554','100k / Q401 B-E bleed',88.9,88.9,'FAULT_BASE','GND')
    d.r('R555','47k / release base limit',228.6,147.32,'ARM_LATCH','RELEASE_BASE')
    d.r('R556','100k / Q402 B-E bleed',228.6,175.26,'RELEASE_BASE','GND')
    d.tp('TP402',330.2,175.26,'HIL_FAULT_N')
    d.s.text('HIL_ARM is generated by the powered HOST, NOT an expansion rail. Q401 defaults ON while HOST requests ARM.',25.4,218.44)
    d.s.text('Only a power-qualified ARM_LATCH turns Q402 on and releases Q401. Board power lost -> Q402 off -> Q401 reports fault.',25.4,228.6)
    d.s.text('HIL_FAULT_N=HIGH means power-qualified AND armed; LOW also means disarmed. At HOST off, no expansion supply drives this pin high.',25.4,238.76)
    d.s.text('Nominal fault sink <0.33mA and HOST ARM total load <0.4mA. Check transient/partial-power behavior physically; not certified safety.',25.4,248.92)
    d.s.text('Other direct DAC/ADC pins STILL require power-off backfeed protection. This diagnostic alone does not authorize hot plugging.',25.4,259.08)
    return d


def remove_old_status(text):
    items=list(expressions(text));out=[];i=0;found=False
    while i<len(items):
        item=items[i]
        if item.startswith('(symbol ') and '(property "Reference" "U409"' in item:
            found=True;i+=1
            while i<len(items) and items[i].startswith(('(wire ','(global_label ','(no_connect ')):i+=1
            continue
        out.append(item);i+=1
    if not found:raise ValueError('U409 removal target missing')
    return '(kicad_sch\n'+'\n'.join(out)+'\n)\n'


def graphics(text):
    def line(points):
        return '(polyline (pts '+''.join(f'(xy {x} {y})' for x,y in points)+') (stroke (width 0.254) (type default)) (fill (type none)))'
    shapes={
      'D':line([(-2.54,-2.54),(-2.54,2.54)])+' '+line([(-2.54,0),(2.54,2.54),(2.54,-2.54),(-2.54,0)]),
      'F':'(rectangle (start -2.54 1.27) (end 2.54 -1.27) (stroke (width 0.254) (type default)) (fill (type none))) '+line([(-2.54,0),(2.54,0)]),
      'SW':line([(-2.54,0),(1.905,2.54)])+' (circle (center -2.54 0) (radius 0.508) (stroke (width 0.254) (type default)) (fill (type none))) (circle (center 2.54 0) (radius 0.508) (stroke (width 0.254) (type default)) (fill (type none)))',
      'TESTPOINT':'(circle (center 0 0) (radius 2.54) (stroke (width 0.254) (type default)) (fill (type none)))',
    }
    shapes['L']=' '.join(f'(arc (start {a} 0) (mid {a+0.635} 0.635) (end {a+1.27} 0) (stroke (width 0.254) (type default)) (fill (type none)))' for a in [-2.54,-1.27,0,1.27])
    for name,shape in shapes.items():
        marker='(symbol "'+name+'_0_1"'
        if marker in text:
            a,b,_=block(text,marker);text=text[:a]+marker+' '+shape+')'+text[b:]
    return text


def finalize():
    sentinel=DST/'POWER_REVIEW_CHECKPOINT.md'
    if sentinel.exists():raise ValueError('already applied: do not overwrite native edits')
    p=DST/'40_power_supervision.kicad_sch';s=p.read_text()
    s=replace_once(s,'(global_label "INPUT_OK" (shape bidirectional) (at 444.5 271.78 180)',
                     '(global_label "HIL_ARM" (shape bidirectional) (at 444.5 271.78 180)')
    s=remove_old_status(s)
    s=s.replace('HIL_FAULT_N is open-drain; require HOST-side pull-up. It reports POWER only.',
                'Host-referenced fault diagnostic is on sheet41; it is not a safety watchdog.')
    p.write_text(s)
    expected=json.loads((DST/'expected_connections.json').read_text())
    expected={key:value for key,value in expected.items() if not key.startswith('U409.')}
    expected['U408.6']='HIL_ARM'
    (DST/'expected_connections.json').write_text(json.dumps(expected,sort_keys=True,indent=2)+'\n')
    STAGES['status']=power_status_sheet;migrate('status')
    for p in [*DST.glob('*.kicad_sch'),DST/'revb.kicad_sym']:
        s=p.read_text()
        for name in ['LT3045_MSE','LT3094_MSE']:
            s=modify_ldo(s,('RevB:' if p.suffix=='.kicad_sch' else '')+name)
        s=graphics(s)
        if p.name=='10_input_protection.kicad_sch':
            a,b,part=block(s,'(symbol (lib_id "RevB:C") (at 274.32 91.44')
            if '(property "Reference" "C105"' not in part:raise ValueError('C105 target changed')
            part=part.replace('Capacitor_SMD:C_0805_2012Metric','Capacitor_SMD:C_2220_5750Metric')
            s=s[:a]+part+s[b:]
        p.write_text(s)
    footprints=set()
    for page in DST.glob('*.kicad_sch'):
        footprints.update(re.findall(r'\(property "Footprint" "([^"\n]+)"',page.read_text()))
    libraries=set()
    for name in sorted(footprints):
        lib,part=name.split(':',1)
        source=Path('/usr/share/kicad/footprints')/(lib+'.pretty')/(part+'.kicad_mod')
        if not source.is_file():raise ValueError('assigned footprint does not exist: '+name)
        dest=DST/'footprints'/(lib+'.pretty')/source.name;dest.parent.mkdir(parents=True,exist_ok=True)
        shutil.copyfile(source,dest);libraries.add(lib)
    license=Path('/usr/share/doc/kicad-footprints/copyright')
    if not license.is_file():raise ValueError('KiCad footprint redistribution license missing')
    shutil.copyfile(license,DST/'footprints/KICAD_FOOTPRINTS_COPYRIGHT')
    table='(fp_lib_table\n (version 7)\n'+'\n'.join(f' (lib (name "{lib}") (type "KiCad") (uri "${{KIPRJMOD}}/footprints/{lib}.pretty") (options "") (descr "KiCad installed footprint snapshot; see COPYRIGHT"))' for lib in sorted(libraries))+'\n)\n'
    (DST/'fp-lib-table').write_text(table)
    for name in ['generated_bom.csv','manifest.json']:(DST/name).unlink(missing_ok=True)
    sentinel.write_text('''# Native power schematic checkpoint

Input, positive rails, negative rail/reference, rail supervisors, latched re-arm
and host-referenced power-status circuits are physically represented.
LOW HIL_ARM immediately holds DAC_RESET_N LOW. Power fault clears the latch;
a fresh ARM edge after rail qualification is required.

Q401/Q402 replace the incomplete open-drain status interface. Status pull-up
energy comes from HOST HIL_ARM, not an expansion supply. Powered-off expansion
cannot report healthy merely because its output is floating. Transient and
partial-power behavior still require bench measurement.

OUT11/OUT12 of each LDO remain connected. One power_out and one passive duplicate
pad model the same internal output, not independent regulators shorted together.
Footprints are locally registered instead of suppressing ERC warnings.
Unassigned regulator/DAC land patterns and exact L/C MPNs remain review items.
The 47uF input ceramic uses a large2220 review footprint, not an implausible0805;
effective DC-bias capacitance must still be substantiated.

Complete HIL watchdog, AO disconnect and DUT gate inhibit are NOT implemented by
this power checkpoint. HIL_WDI terminates at TP401 only. ADC/PHY are deferred.
No board startup, surge, thermal, ripple or FOC hardware PASS is claimed.
''')
    print('Targeted native repairs applied; editable child sheets retained.')


if __name__=='__main__':finalize()
